services:
  - type: web
    name: zofio-backend
    env: node
    buildCommand: cd src/zofio_backend && npm install
    startCommand: cd src/zofio_backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
